name: Fetch new plugins from awesome-neovim

on:
  schedule:
    - cron: "22 19 * * 2,5"
  workflow_dispatch:
permissions: write-all
jobs:
  fetch-new-plugins:
    runs-on: ubuntu-latest
    name: Fetch new plugins from awesome-neovim
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix run .#update-vim-plugins -- awesome-neovim
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'maintenance: auto fetch awesome neovim plugins'
          file_pattern: manifest.txt
          push_options: '--force'
