name: Update plugins

on:
  push:
    paths:
      - manifest.txt
      - blacklist.txt
      - whitelist.txt
    branches:
      - main
  schedule:
    - cron: "5 14 * * 0,4"
  workflow_dispatch:
permissions: write-all
jobs:
  update-plugins:
    runs-on: ubuntu-latest
    name: Update plugins
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - run: nix run .#update-vim-plugins -- update --all
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          SOURCEHUT_TOKEN: ${{ secrets.SOURCEHUT_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'maintenance: auto update plugins'
          file_pattern: README.md pkgs/vim-plugins.nix .previous-update.json
          push_options: '--force'
